name: Build and Push

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: s3 sync
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ secrets.S3_BUCKET_REGION }}"
          AWS_S3_BUCKET: "${{ secrets.S3_BUCKET }}"
          SOURCE_DIR: "."
